project_id = "qdbldrlzabqcuadlkyoy"

[functions.simulate-smile]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.perfect-corp-analysis]
verify_jwt = false

[functions.flow-payment]
verify_jwt = false

[functions.flow-webhook]
verify_jwt = false